"""
gRPC TierAgent server skeleton.

Intentionally does NOT import the generated stubs — run the protoc build step
first (see __init__.py). This file describes the wiring an implementer would
fill in.

Responsibilities when implemented:
  - Bind a single TierAgentServicer instance that accepts "tier1|tier2|tier3"
    requests and dispatches to the corresponding local analyst.
  - Reuse the Tier1Analyst / Tier2Analyst / Tier3Analyst instances from
    LegacyCompat so the dispatch logic matches the in-process path.
  - Report queue_depth + mean_latency_ms in the Health RPC so the orchestrator
    can circuit-break away from degraded tiers.

CLI:
    python -m Implementation.src.Agents.grpc.tier_agent_server --tier tier1 --port 7051
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from concurrent import futures

logger = logging.getLogger(__name__)


def _import_stubs():
    """Imports the generated gRPC stubs, or raises with a helpful hint."""
    try:
        # These modules are generated by protoc; won't exist until compiled.
        from . import tier_agent_pb2, tier_agent_pb2_grpc  # type: ignore
        return tier_agent_pb2, tier_agent_pb2_grpc
    except ImportError as exc:
        raise ImportError(
            "gRPC stubs not generated yet. Run:\n"
            "  python -m grpc_tools.protoc -I Implementation/src/Agents/grpc "
            "--python_out=Implementation/src/Agents/grpc "
            "--grpc_python_out=Implementation/src/Agents/grpc "
            "Implementation/src/Agents/grpc/tier_agent.proto"
        ) from exc


def make_servicer(tier: str):
    pb2, pb2_grpc = _import_stubs()
    import json, time

    class TierAgentServicer(pb2_grpc.TierAgentServicer):  # type: ignore
        def __init__(self):
            # Lazy import — avoid pulling in torch unless this microservice runs
            from Implementation.src.Agents.LegacyCompat import (
                Tier1Analyst, Tier2Analyst, Tier3Analyst,
            )
            api_key = os.getenv("RAGARENN_API_KEY")
            self._analyst = {
                "tier1": lambda: Tier1Analyst(api_key=api_key),
                "tier2": lambda: Tier2Analyst(api_key=api_key),
                "tier3": lambda: Tier3Analyst(api_key=api_key),
            }[tier]()
            self._latency_samples: list[float] = []

        def Process(self, request, context):
            t0 = time.time()
            payload = json.loads(request.payload_json or "{}")
            try:
                result = self._analyst.process(payload)
                elapsed = int((time.time() - t0) * 1000)
                self._latency_samples = (self._latency_samples + [elapsed])[-64:]
                return pb2.ProcessResponse(
                    alert_id=request.alert_id,
                    tier=tier,
                    result_json=json.dumps(result, default=str),
                    is_final=True,
                    elapsed_ms=elapsed,
                )
            except Exception as exc:
                return pb2.ProcessResponse(
                    alert_id=request.alert_id,
                    tier=tier,
                    result_json=json.dumps({"error": f"{type(exc).__name__}: {exc}"}),
                    is_final=True,
                    fallback_reason="handler_exception",
                )

        def ProcessStream(self, request_iterator, context):
            for req in request_iterator:
                yield self.Process(req, context)

        def Health(self, request, context):
            mean = (sum(self._latency_samples) / len(self._latency_samples)) if self._latency_samples else 0.0
            return pb2.HealthResponse(
                status="serving",
                tier=tier,
                version="scaffold-0.1",
                queue_depth=0,
                mean_latency_ms=float(mean),
            )

    return TierAgentServicer()


def serve(tier: str, port: int) -> int:
    import grpc  # type: ignore
    pb2, pb2_grpc = _import_stubs()
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=16))
    pb2_grpc.add_TierAgentServicer_to_server(make_servicer(tier), server)
    server.add_insecure_port(f"[::]:{port}")
    server.start()
    logger.info("TierAgent gRPC server on :%d serving tier=%s", port, tier)
    server.wait_for_termination()
    return 0


def _cli() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tier", choices=("tier1", "tier2", "tier3"), required=True)
    ap.add_argument("--port", type=int, default=7051)
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO)
    return serve(args.tier, args.port)


if __name__ == "__main__":
    sys.exit(_cli())
