"""
Purple Team Agent (Coordinator / Optimiser)
============================================
Coordinates Red/Blue exercises and analyses results to improve the
overall security posture.  Acts as the mediator between attack and
defence perspectives.
"""

from langchain_mistralai import ChatMistralAI
from langchain_core.messages import AIMessage
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import StateGraph, MessagesState, START, END
from langgraph.prebuilt import ToolNode, tools_condition
from .HexstrikeClient import HexstrikeClient
from .HexstrikeTools import get_hexstrike_tools
from typing import Dict, Any
import os
import json
import uuid
import datetime

# ---------------------------------------------------------------------------
# Configuration – loaded once at module level
# ---------------------------------------------------------------------------

try:
    _config_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        "config.json",
    )
    with open(_config_path, "r") as _f:
        _config = json.load(_f)
except (FileNotFoundError, json.JSONDecodeError) as exc:
    print(f"Warning: Config load failed: {exc}")
    _config = {}

# System prompt defining the Purple Team Lead's responsibilities
_SYSTEM_PROMPT = """\
You are the Purple Team Lead (Coordinator).
Your goal is to maximise the effectiveness of the security posture
by coordinating Red (Attack) and Blue (Defense) teams.

Capabilities:
1. Analyse the outcome of Red vs Blue exercises.
2. Identify gaps where Blue failed to stop Red.
3. Identify gaps where Red failed to find vulnerabilities.
4. Generate "Lessons Learned" and actionable recommendations.
"""


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------

class PurpleTeamAgent:
    """
    Purple Team agent – coordinates Red/Blue exercises and synthesises
    the results into actionable security recommendations.
    """

    def __init__(self, api_key: str = None):
        """
        Initialise the Purple Team agent.

        Args:
            api_key: Mistral API key. Falls back to the MISTRAL_API_KEY env var.
        """
        from dotenv import load_dotenv
        load_dotenv()

        api_key = api_key or os.getenv("MISTRAL_API_KEY")

        # LLM setup (disabled gracefully when no key is available)
        self.llm = (
            ChatMistralAI(
                model=_config.get("Model", "mistral-large-latest"),
                api_key=api_key,
                temperature=0.2,
                timeout=60,
            )
            if api_key
            else None
        )

        self.memory = MemorySaver() if api_key else None

        # Build and compile the LangGraph workflow
        if api_key and self.tools:
            self.llm = getattr(self.llm, 'bind_tools', lambda x: self.llm)(self.tools)

        if api_key:
            self.graph = self._create_graph()
            self.app = self.graph.compile(checkpointer=self.memory)
        else:
            self.app = None

    # ── Graph construction ──────────────────────────────────────────────

    def _create_graph(self) -> StateGraph:
        """Create a single-node graph for the coordinator LLM call."""
        workflow = StateGraph(MessagesState)
        workflow.add_node("coordinator", self._call_model)

        try:
            workflow.set_entry_point("coordinator")
        except AttributeError:
            workflow.add_edge("__start__", "coordinator")

        try:
            workflow.add_node("tools", ToolNode(self.tools))
        workflow.add_conditional_edges("coordinator", tools_condition)
        workflow.add_edge("tools", "coordinator")
        except AttributeError:
            workflow.add_node("tools", ToolNode(self.tools))
        workflow.add_conditional_edges("coordinator", tools_condition)
        workflow.add_edge("tools", "coordinator")

        return workflow

    # ── LLM invocation ──────────────────────────────────────────────────

    def _call_model(self, state: MessagesState):
        """Invoke the LLM with the Purple Team system prompt."""
        if not self.llm:
            return {"messages": []}

        last_message = state["messages"][-1].content
        messages = [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": last_message},
        ]
        response = self.llm.invoke(messages)
        return {"messages": [AIMessage(content=getattr(response, "content", str(response)))]}

    # ── Public API ──────────────────────────────────────────────────────

    def analyze_exercise(
        self, red_output: Dict[str, Any], blue_output: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Analyse the results of a Red/Blue team exercise.

        Args:
            red_output: Outputs generated by the Red Team agent.
            blue_output: Outputs generated by the Blue Team agent.

        Returns:
            Dictionary containing the analysis report and a timestamp.
        """
        prompt = (
            "Analyze this War Game Exercise:\n\n"
            "Red Team (Attacker) Plan & Output:\n"
            f"{json.dumps(red_output, indent=2)}\n\n"
            "Blue Team (Defender) Plan & Output:\n"
            f"{json.dumps(blue_output, indent=2)}\n\n"
            "Provide a comprehensive report:\n"
            "1. Who won? (Did the attack succeed?)\n"
            "2. What were the key vulnerabilities?\n"
            "3. How effective were the defenses?\n"
            "4. Recommendations for improvement."
        )

        report = "LLM disabled."

        if self.app:
            try:
                thread_id = str(uuid.uuid4())
                cfg = {"configurable": {"thread_id": thread_id}}
                result = None
                for event in self.app.stream(
                    {"messages": [{"role": "user", "content": prompt}]},
                    cfg,
                    stream_mode="values",
                ):
                    result = event.get("messages", [])
                report = result[-1].content if result else ""
            except Exception as exc:
                report = f"Error in Purple Team processing: {exc}"

        return {
            "analysis_report": report,
            "timestamp": datetime.datetime.utcnow().isoformat(),
        }
