"""
Remediation Agent
Responsible for executing defensive rules and scripts generated by the Blue Team.
Supports Dry Run mode to log intended actions safely.
"""

import json
import logging
import os
import datetime
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)

class RemediationAgent:
    """
    Executes or simulates the execution of defensive measures.
    """
    
    def __init__(self, dry_run: bool = True):
        self.dry_run = dry_run
        # Resolve output directory to project root (Project/Reports)
        # Using a more robust way to find root: look for .env or go up 4 levels
        current_file = os.path.abspath(__file__)
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(current_file))))
        self.reports_dir = os.path.join(base_dir, "Reports")
        self.log_path = os.path.join(self.reports_dir, "remediation_log.json")
        
        if not os.path.exists(self.reports_dir):
            os.makedirs(self.reports_dir, exist_ok=True)
            
        logger.info(f"RemediationAgent initialized. Log path: {self.log_path}")
        print(f"DEBUG: RemediationAgent Log path: {self.log_path}")

    def process(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Main entry point for the agent.
        """
        threat_info = input_data.get("threat_info", {})
        code = input_data.get("generated_code", "")
        plan = input_data.get("defense_plan", "")
        
        logger.info(f"RemediationAgent: Processing remediation for threat: {threat_info.get('Attack', 'Unknown')}")
        
        # Parse actionable rules from plan
        rules = self._parse_rules(plan)
        
        execution_result = self.apply_remediation(threat_info, code, plan, rules)
        
        return {
            "remediation_status": execution_result.get("status"),
            "execution_log": execution_result,
            "enforced_rules": rules,
            "timestamp": datetime.datetime.utcnow().isoformat()
        }

    def _parse_rules(self, text: str) -> list:
        """Extracts JSON rules from text block [ACTIONABLE_RULES]...[/ACTIONABLE_RULES]."""
        import re
        try:
            # Case insensitive search with DOTALL
            pattern = r"\[ACTIONABLE_RULES\](.*?)\[/ACTIONABLE_RULES\]"
            match = re.search(pattern, text, re.DOTALL | re.IGNORECASE)
            
            if match:
                content = match.group(1).strip()
                logger.info(f"Identified rule segment length: {len(content)}")
                
                # 1. Heavily strip common LLM junk
                content = re.sub(r"```(?:json)?", "", content)
                content = content.replace("```", "").replace("**", "").strip()
                
                # 2. Extract ONLY the JSON part (from first [ or { to last ] or })
                # This makes it resilient to LLM "chatter" inside the tags
                json_match = re.search(r"(\[.*\]|\{.*\})", content, re.DOTALL)
                if json_match:
                    json_str = json_match.group(1).strip()
                    try:
                        rules = json.loads(json_str)
                        if isinstance(rules, list):
                            return rules
                        return [rules]
                    except json.JSONDecodeError as je:
                        logger.error(f"JSON decode failed on extracted content: {je}")
                        # Fallback: try to find common key-value patterns if JSON failed
            
        except Exception as e:
            logger.warning(f"General rule parsing exception: {e}")
        return []

    def apply_remediation(self, threat_info: Dict[str, Any], code: str, plan: str, rules: list = None) -> Dict[str, Any]:
        """
        Records the remediation attempt.
        """
        log_entry = {
            "timestamp": datetime.datetime.utcnow().isoformat(),
            "threat": threat_info,
            "planned_defense": plan,
            "enforced_rules": rules or [],
            "code_provided": bool(code),
            "dry_run": self.dry_run,
            "status": "SIMULATED_SUCCESS" if self.dry_run else "EXECUTED"
        }
        
        # In a real scenario, this is where we would subprocess.run(script) 
        # or call a firewall API. For safety, we log it.
        
        try:
            current_logs = []
            if os.path.exists(self.log_path):
                with open(self.log_path, 'r') as f:
                    try:
                        current_logs = json.load(f)
                    except json.JSONDecodeError:
                        current_logs = []
            
            current_logs.append(log_entry)
            
            with open(self.log_path, 'w') as f:
                json.dump(current_logs, f, indent=2)
                
            logger.info(f"Remediation log updated at {self.log_path}")
            return log_entry
        except Exception as e:
            logger.error(f"Failed to log remediation: {e}")
            return {"status": "ERROR", "error": str(e)}

if __name__ == "__main__":
    # Quick standalone test
    agent = RemediationAgent()
    print(agent.process({
        "threat_info": {"Attack": "DDoS", "SourceIP": "192.168.1.100"},
        "generated_code": "iptables -A INPUT -s 192.168.1.100 -j DROP",
        "defense_plan": "Block the source IP using iptables."
    }))
